# Generated by Django 4.0.6 on 2022-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
